name: 自动构建

on:
  schedule:
    - cron: '0 0-23 * * *'

jobs:
  deployJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # 定时任务需要指定分支
        with: { ref: main }
      - run: yarn
      - run: npm run dist
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
