name: version

on:
  push:
    branches:
      - main

jobs:
  version:
    name: version
    runs-on: ubuntu-latest
    steps:
      - name: 切换分支
        uses: actions/checkout@v3
        with: { ref: main }
      - name: 配置 git
        run: |
          git config --local user.email "2326962137@qq.com"
          git config --local user.name "action-bot"
      - name: 合并&转换
        run: |
          node version.js
          git add .
          git commit -a -m "更新版本号 $(date +"%D %T")"
      - name: 推送
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
